### ISSUE TITLE
Unable to generate code when using Custom Validation Rules

### ISSUE THREAD

**Issue by evolvoltd** [Mezatsong/laravel-swagger-docs#3]
Steps to reproduce:
1. php artisan make:rule CustomStringValidationRule
2. add rule to FormRequest rules array 'title'=>['string', new CustomStringValidationRule]
3. php artsian swagger:generate
Result  str_starts_with(): Argument #1 ($haystack) must be of type string, App\Rules\CustomStringValidationRule given

**Comment by Mezatsong** [comment]
Thank you for fix merge request https://github.com/Mezatsong/laravel-swagger-docs/pull/4
The error has been fixed
